#!/data/data/com.termux/files/usr/bin/bash

# Copyright 2017-2019 by YadominJinta. All rights reserved.
# https://github.com/YadominJinta/atilo has info about the project.
# https://github.com/YadominJinta/atilo/blob/master/CONTRIBUTORS.md Thank you for help.
# _STANDARD_="function name" && STANDARD="variable name" are under construction
####################################################################################

# Declear Variables
VER=2.0-dev
ATILO_DIR=$HOME/.atilo
ATILO_TMP=$ATILO_DIR/tmp
ATILO_CONFIG=$PREFIX/etc/atilo

# Create Basic Files
if [ ! -d $ATILO_TMP ];then
    mkdir -p $ATILO_TMP
fi

if [ ! -d $ATILO_CONFIG ];then
	mkdir $ATILO_CONFIG	
fi


# Init Functions
_PUT_()
{
    echo -e "\033[32m$@\033[0m"
}

_ERR_()
{
    echo -e "\033[1;31m$@\033[0m" 1>&2
    exit 1
}

_UP_LOCALES_()
{
	j=1
	LIST=$(curl https://raw.githubusercontent.com/YadominJinta/atilo/dev/src/locales/list)
	for i in $LIST
	{
	 	_OUT_ "$j $i" 
		 k[j]=$i
		j=`expr $j += 1`
	}
	_OUT_ "Choose a language:"
	read a
	curl -o $ATILO_CONFIG/locales "https://raw.githubusercontent.com/YadominJinta/atilo/dev/src/locales/$k[a]"
	chmod +x $ATILO_CONFIG/sources
}

_UP_SOURCES_()
{
	j=1
	$LIST=$(curl https://raw.githubusercontent.com/YadominJinta/atilo/dev/src/sources/list)
	for i in $LIST
	{
		
	 	_OUT_ "$j $i" 
		 k[j]=$i
		j=`expr $j += 1`
	}
	_OUT_ "Choose a source:"
	read a
	curl -o $ATILO_CONFIG/sources "https://raw.githubusercontent.com/YadominJinta/atilo/dev/src/sources/$k[a]"
	chmod +x $ATILO_CONFIG/sources
	}
}

_CHK_ARCH_()
{
    	case `dpkg --print-architecture` in
		aarch64)
			ARCH="arm64" ;;
		arm)
			ARCH="armhf" ;;
		amd64)
			ARCH="amd64" ;;
		i*86)
			ARCH="i386" ;;
		x86_64)
			ARCH="amd64" ;;
		*)
			_ERR_ "" ;;
		esac
}

_GET_HELP_()
{
	_OUT_ "Atilo \t $VER "
	_OUT_ "$WORD[0]\n"
	_OUT_ "$WORD[1]"
	_OUT_ "$WORD[2]"
	_OUT_ "list\t\t $WORD[3]"
	_OUT_ "   --installed   $WORD[4]"
	_OUT_ "remove\t\t $WORD[5]"
	_OUT_ "install\t\t $WORD[6]"
	_OUT_ "clean\t\t $WORD[7]"
	_OUT_ "set\t\t $WORD[8]"
	_OUT_ "help\t\t $WORD[9]\n"
	_OUT_ "$WORD[10]"
}

_SHOW_MOO_()
{
	_OUT_ "
                 (__) 
                 (oo) 
           /------\/ 
          / |    ||   
         *  /\---/\ 
            ~~   ~~   
		$WORD[11]"
}

_GET_LIST_()
{
	_OUT_ "$WORD[12]\n"
	for i in $LIUNX_LIST[@]
	{
		_OUT_ $i
	}
}

_GET_LOCAL_()
{
	_OUT_ "$WORD[13]"
	cd $ATILO_DIR
	for i in $(ls ./)
	do
		if [ $i != "tmp" ]; then
			_OUT_ $i
		fi
	done
}

_REMOVE_LINUX_()
{
	cd $ATILO_DIR
	if [ -d $SELECTED ];then
		_OUT_ "$WORD[14] $SELECTED [y/n]"
		read a
		if [ $a == "y" ];then
			chmod -R 0755 $SELECTED
			rm -rf $SELECTED
			rm $PREFIX/bin/start$SELECTED
			_OUT_ "WORD[15]"
		else
			exit 1
		fi
	else
		_ERR_ "$WORD[16] $SELECTED"
	fi
}

_REMOVE_TMPS_()
{
	_OUT_ $WORD[17]
	rm -rf $ATILO_TMP/*
}

_DOWNLOAD_SELECTED_()
{
	if [ -f $ATILO_TMP/$SELECTED ];then
		_OUT_ $WORD[18]
		cd $ATILO_DIR
		curl $URL -o $SELECTED --progress -C -
	else
		_OUT_ $WORD[19]
	fi
}

_MAIN_()
{
	#Load Locales
	if [ -f $ATILO_CONFIG/locales ];then
		source $ATILO_CONFIG/locales
	else
		_UP_LOCALES_
	fi

	#Load Sources
	if [ -f $ATILO_CONFIG/sources];then
		source $ATILO_CONFIG/sources
	else
		_UP_SOURCES_
	fi

	# Choose a command
	case $1 in 
		help)
			_GET_HELP_
			;;
		moo)
			_SHOW_MOO_
			;;
		list|ls)
			if [ $2 == "--installed" ];then
				_GET_LOCAL_
			else
				_GET_LIST_
			fi
			;;
		install|in)
			_CHK_ARCH_
			_INSTALL_LINUX_
			;;
		remove|rm)
			_REMOVE_LINUX_
			;;
		clean)
			_REMOVE_TMPS_
			;;
		set)
			_UP_LOCALES_
			_UP_SOURCES_
			;;
		"")
			_GET_HELP_
			_ERR_ "$WORD[20]"
			;;
		*)
			_ERR_ "$WORD[21]"
			;;
		esac
}

_MAIN_ "$@"